# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'vmagent'

stages:
- stage: Build
  jobs:
  - job: Build_and_Publish
    steps:
    - task: UseDotNet@2  # Use the appropriate .NET task for your project
      inputs:
        version: '8.x'  # Adjust version based on your .NET framework
        includePreviewVersions: true  # Optional for preview versions

    - task: DotNetCoreCLI@2  # Use the appropriate task for building
      inputs:
        command: 'build'
        configuration: $(buildConfiguration)
        projects: '**/*.csproj'  # Adjust project path if needed

    - task: DotNetCoreCLI@2  # Use the appropriate task for publishing
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishPipelineArtifact@1  # Publish build artifacts
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'dotnet-app'

- stage: Deploy
  jobs:
  - job: Deploy_to_VM
    steps:
    - task: DownloadPipelineArtifact@1  # Download build artifacts
      inputs:
        buildType: 'current'
        artifactName: 'dotnet-app'
        targetPath: '$(System.DefaultWorkingDirectory)/app'

    - script: |  # Script to deploy on VM (replace with your specific commands)
        sudo apt-get update
        sudo apt-get install -y nginx  # Example: Install web server
        sudo cp -r $(System.DefaultWorkingDirectory)/app/* /var/www/html/  # Example: Copy files
        sudo systemctl restart nginx  # Example: Restart web server


- stage: Copyfiles
  jobs:
  - job: copyfiles_to_azure
    steps:
    - task: AzureFileCopy@2
      inputs:
        SourcePath: '/var/www/html/'
        azureSubscription: 'Free Trial(1)(a25d286e-68a4-4c24-8d88-d34e1a49ee20)'
        Destination: 'AzureBlob'
        storage: 'dotapp'
        ContainerName: 'appproj'
        