# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build_and_Publish
    steps:
    - task: UseDotNet@2  # Use the appropriate .NET task for your project
      inputs:
        version: '8.x'  # Adjust version based on your .NET framework
        includePreviewVersions: true  # Optional for preview versions

    - task: DotNetCoreCLI@2  # Use the appropriate task for building
      inputs:
        command: 'build'
        configuration: $(buildConfiguration)
        projects: '**/*.csproj'  # Adjust project path if needed

    - task: DotNetCoreCLI@2  # Use the appropriate task for publishing
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy_to_VM
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - script: |  # Script to deploy on VM (replace with your specific commands)
        sudo apt-get update
        sudo apt-get install -y nginx  # Example: Install web server
        sudo cp -r $(System.ArtifactsDirectory)/app/* /var/www/html/  # Example: Copy files
        sudo systemctl restart nginx  # Example: Restart web server

     - task: AzureFileCopy@6
       inputs:
         SourcePath: '/var/www/html/'
         azureSubscription: 'Free Trial(1)(a25d286e-68a4-4c24-8d88-d34e1a49ee20)'
         Destination: 'AzureBlob'
         storage: 'dotapp'
         ContainerName: 'appproj'
